apiVersion: v1
kind: Service
metadata:
  name: {{ include "gerrit.fullname" . }}
  labels:
    {{- include "gerrit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - port: {{ .Values.service1.port1 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gerrit.selectorLabels" . | nindent 4 }}
