--- 
affinity: {}
autoscaling: 
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ""
image: 
  pullPolicy: Always
  repository: drupal
  repository1: postgres
  tag: ""
imagePullSecrets: []
ingress: 
  annotations: {}
  enabled: false
  hosts: 
    - 
      host: chart-example.local
      paths: []
  tls: []
limits: 
  cpu: 100m
  memory: 128Mi
  requests: 
    cpu: 100m
    memory: 128Mi
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service: 
  port: 80
  type: NodePort
serviceAccount: 
  annotations: {}
  create: true
  name: root
tolerations: []
